// This file is auto-generated by "yarn tailwindcss init -p"
// For more info about Tailwind init, see: https://tailwindcss.com/docs/guides/nextjs
// If you want to use other PostCSS plugins, see: https://tailwindcss.com/docs/using-with-preprocessors

module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
